spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpetstore
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  servlet:
    context-path: /jpetstore
  port: 8090

logging:
  file:
    path: log
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zlp.jpetstore_spring.entity
  configuration:
    map-underscore-to-camel-case: true
