spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpetstore
    username: Raymond
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password:
      timeout: 5s

server:
  servlet:
    context-path: /jpetstore
  port: 8080


logging:
  file:
    path: log

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com/example/jpetstore/POJO/DataObject
  configuration:
    map-underscore-to-camel-case: true
